batch_size: 4096
data_dir: Rosykunai/SGEMM_GPU_performance
decay_every: 20
epochs: 100
in_features: 14
lr: 2.0e-07
lr_decay: 0.995
out_features: 1
results_path: null
seed: 123
shuffle: true
task: Regression
